name: Run Server Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can keep this as it is since you're using Node.js, but on Windows you can switch to windows-latest
    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.4.1'  

      - name: Install dependencies
        run: |
          cd server
          npm install  # Install server dependencies

      - name: Set up MongoDB URI for tests
        run: echo "MONGO_TEST_URL= mongodb+srv://marhranim:123@cluster0.d66pi.mongodb.net/" > server/.env  

      - name: Run tests
        run: |
          cd server
          npm run test:server  # Run server tests
