name: MERN CI Pipeline

# Controls when the action will run.
on:
  push:
    branches: [ main ] # Run the CI on push to the main branch
  pull_request:
    branches: [ main ] # Also run CI on pull requests to the main branch

# Define the jobs for this workflow
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017
        options: --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'" --health-interval=10s --health-timeout=5s --health-retries=5

    strategy:
      matrix:
        node-version: [14.x, 16.x] # Specify Node.js versions to test on

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Set up MongoDB URI for tests
        run: echo "mongodb+srv://marhranim:123@cluster0.d66pi.mongodb.net/" > .env.test

      - name: Run backend tests
        run: npm run test:server

      - name: Run linting
        run: npm run lint
