name: Run Server Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      # Step 3: Install server dependencies
      - name: Install dependencies
        run: |
          cd server
          npm install

      # Step 4: Set environment variables
      - name: Set environment variables for Braintree and MongoDB
        run: |
          echo "PORT=8080" > server/.env
          echo "NODE_ENV=test" >> server/.env  # Set NODE_ENV to test during CI runs
          echo "MONGO_URL=mongodb+srv://storedb:123@cluster0.yuzsf2m.mongodb.net/" >> server/.env
          echo "MONGO_TEST_URL=mongodb+srv://marhranim:123@cluster0.d66pi.mongodb.net/" >> server/.env
          echo "JWT_SECRET=cosanostra123" >> server/.env
          echo "BRAINTREE_MERCHANT_ID=djf5xy7wpyrn2xhq" >> server/.env
          echo "BRAINTREE_PUBLIC_KEY=sy5zqpyjbbgvpqpm" >> server/.env
          echo "BRAINTREE_PRIVATE_KEY=6044dd4c4e13698f87f9cb36c6d4742a" >> server/.env

      # Step 5: Run the tests
      - name: Run server tests
        run: |
          cd server
          npm run test:server
